apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-sonar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonar
  template:
    metadata:
      labels:
        app: sonar
    spec:
      containers:
      - name: sonar-container
        image: sonarqube
        ports:
        - containerPort: 9000
