apiVersion: v1
kind: Service
metadata: 
  name: sonarqube
spec:
  type: NodePort
  selector: 
    app: soanr
  ports:
  - name: sonar-port
    protocol: TCP      
    port: 9000
    targetPort: 9000
    nodePort: 30005
