apiVersion: apps/v1
kind: Deployment
metadata: 
  name: sonar

spec:
  replicas: 3 
  selector: 
    matchLabels: 
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec: 
      containers: 
      - name: sonarqube-container
        image: sonarqube
        ports: 
        - containerPort: 9000
