
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx-new
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployed
  template:
    metadata:
      labels:
        app: deployed
    spec:
      containers:
      - name: deploy-nginx-container
        image: nginx:latest
        ports:
        - containerPort: 80
