apiVersion: apps/v1

kind: Deployment

metadata: 
  name: httpd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpd-test
  template:
    metadata:
      labels:
        app: httpd-test
    spec:
      containers:
      - name: httpd-service
        image: httpd
        ports:
        - name: httpd-port
          containerPort: 80
          protocol: TCP
