apiVersion: v1


kind: Pod

metadata:
        name: my-pod
spec:
        containers:
                - name: my-container
                  image: busybox
                  command:
                          - sh
                          - '-c'
                          - echo YAY! My definition is successful && sleep 3600
