
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport

spec: 
  type: NodePort
  selector:
    app: net-1
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 80
    nodePort: 30005
