
apiVersion: v1
kind: Service
metadata: 
  name: nginx-lb
spec:
  type: LoadBalancer
  externalIPs:
  - 35.209.123.79
  selector: 
    app: nginx-lb
  ports:
  - name:
    protocol: TCP      
    port: 80
    targetPort: 80



