apiVersion: apps/v1
kind: Deployment
metadata: 
  name: deploy-tt
spec: 
  replicas: 4
  selector:
    matchLabels: 
      app: tt
  template: 
    metadata: 
      labels: 
        app: tt
    spec: 
      containers: 
      - name: tt-container
        image: nginx:latest
        ports: 
        - containerPort: 80

          # for using taints use command "kubectl taint node node-1 app=tt:NoSchedule"
          # To remove taints use command "kubectl taint node node-1 app=tt:NoSchedule-"

