apiVersion: v1
kind: Pod
metadata: 
  name: test-probes
  labels: 
    test: probes
spec: 
  containers: 
  - name: test-probe-container
    image: registry.k8s.io/busybox
    command: ['/bin/sh', 'touch /tmp/heatlthy; sleep 30; rm -f /tmp/healthy; sleep 600']
    livenessProbe: 
      exec: 
        command: 
        - cat
        - /tmp/healthy
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe: 
      exec: 
        command: 
        - cat 
        - /tmp/healthy
      initialDelaySeconds: 10
      periodSeconds: 10

