
apiVersion: v1
kind: Pod
metadata:
  name: rd-vol1
spec:
  containers:
  - name: rd-vol1
    image: redis:latest
    volumeMounts:
    - name: rd-volume
      mountPath: /data
  volumes: 
  - name: rd-volume
    emptyDir: {}



