apiVersion: apps/v1
kind: Deployment
metadata: 
  name: ubuntu-version
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: ubuntu
  template:
    metadata:
      labels:
        app: ubuntu
    spec:
      containers:
      - name: ubuntu-containers
        image: ubuntu:20.04
        command: ["sleep", "123456"]
