apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-cm
spec:
  containers:
    - name: ubuntu-cm-container
      image: ubuntu:latest
      command: ["sleep", "3600"]
      volumeMounts:
      - name: config-vol
        mountPath: "/asian-countries"
        readOnly: true
  volumes:
    - name: config-vol
      configMap:
        name: asian-countries


