apiVersion: v1
kind: Service
metadata: 
  name: zk-hs
  labels: 
    app: zk
spec: 
  selector: 
    app: zk
  clusterIP: None
  ports:
  - port: 2888
    name: server
  - port: 3888
    name: leader-election
