apiVersion: v1
kind: Pod
metadata: 
  name: nginx-pv
spec: 
  containers: 
  - name: nginx-pv-container
    image: nginx
    ports: 
    - containerPort: 80
    volumeMounts: 
    - mountPath: "/usr/share/nginx/html"
      name: pv-vol
  volumes: 
  - name: pv-vol
    persistentVolumeClaim: 
      claimName: my-pvc

