apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-pv-deployment
spec: 
  selector: 
    matchLabels: 
      app: pv
  template: 
    metadata: 
      labels: 
        app: pv
    spec: 
      containers: 
      - name: nginx-pv-deploy
        image: nginx
        ports: 
        - containerPort: 80
        volumeMounts: 
        - mountPath: "usr/share/nginx/html"
          name: pv-vol
      volumes: 
      - name: pv-vol
        persistentVolumeClaim: 
          claimName: my-pvc




