apiVersion: v1
kind: Pod
metadata: 
  name: nodejs-sec-ctx
spec: 
  securityContext: 
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
  containers: 
  - name: nodejs-sec-ctx
    image: docker.io/node:latest
    command: [ 'sh', '-c', 'sleep 1h' ]
    securityContext: 
      allowPrivilegeEscalation: false
      capabilities: 
        add: 
        - SYS_ADMIN
        - NET_ADMIN
