
apiVersion: v1
kind: Pod
metadata: 
  name: secure-nginx
spec: 
  containers: 
  - name: secure-nginx-container
    image: nginx:latest
    ports: 
    - containerPort: 80
    securityContext: 
      allowPrivilegeEscalation: false
