apiVersion: v1
kind: Pod
metadata: 
  name: ubuntu-privileged
spec: 
  containers: 
  - name: ubuntu-privileged-container
    image: ubuntu:latest
    command: ["sleep", "1232"]
    securityContext: 
      privileged: true
