apiVersion: v1
kind: Pod
metadata: 
  name: secret-busybox
spec: 
  containers: 
  - name: secret-busybox-container
    image: busybox
    args: 
    - sleep 
    - "3560"
    volumeMounts:
    - mountPath: "/projected-volume/secrets"
      name: projected-vol-01
      readOnly: true
  volumes: 
  - name: projected-vol-01
    projected: 
      sources: 
      - secret: 
          name: user
      - secret: 
          name: password
