apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata: 
  name: viewer
  namespace: system-01

rules: 
 - apiGroups: ["", "apps"]
   resources: ["pods", "replicasets", "deployments"]
   verbs: ["list", "get", "watch"]
