apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata: 
  name: viewer-role-binding
  namespace: system-01

subjects:
  - kind: User
    name: newbie
    apiGroup: rbac.authorization.k8s.io
roleRef: 
  kind: Role
  name: viewer
  apiGroup: rbac.authorization.k8s.io

