
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  type: LoadBalancer
  externalIPs: 
  - 35.209.66.244

  ports:
  - name: mylb-port
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: guestbook
    tier: frontend
