
apiVersion: v1
kind: Service
metadata:
  name: redis-main
  labels:
    app: redis
    role: main
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redis
    role: main
    tier: backend
