apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-dual
spec:
  containers:
    - name: ubuntu-dual-container
      image: ubuntu:20.04
      command: ['sleep', '604800']
      volumeMounts:
        - mountPath: /data
          name: empty-vol
        - mountPath: /vol
          name: host-vol
 
  volumes:
    - name: empty-vol
      emptyDir: {}
    - name: host-vol
      hostPath:
        path: /vol-data
