apiVersion: v1
kind: Pod
metadata: 
  name: test-nginx
spec: 
  containers: 
  - name: test-nginx-container
    image: nginx:latest
    ports: 
    - containerPort: 80
    resources: 
      limits: 
        memory: "1Gi"
        cpu: "500m"
